routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            //Route::get('attributes.partgroups', 'Attributes\AttributeController@partgroups');
            Route::get('partgroups', 'Categories\CategoryController@partgroups')->name('categories.partgroups');
            Route::get('carmodel', 'Categories\CategoryController@carmodel')->name('categories.carmodel');
            Route::get('carsubmodel', 'Categories\CategoryController@carsubmodel')->name('categories.carsubmodel');
            Route::get('carparts', 'Categories\CategoryController@carparts')->name('categories.carparts');
            Route::get('subpart', 'Categories\CategoryController@subpart')->name('categories.subpart');
            Route::get('piece', 'Categories\CategoryController@piece')->name('categories.piece');
            Route::get('assignCarParts', 'Categories\CategoryController@assignCarParts')->name('categories.assignCarParts');
            Route::put('saveParts', 'Categories\CategoryController@saveParts')->name('categories.saveCarParts');
            Route::put('unassign', 'Categories\CategoryController@unassignParts')->name('categories.unassignParts');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');

        });
        Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('language/{slug?}', 'HomeController@language')->name('changeLanguage');
    Route::get('paymentwallresponse', 'CheckoutController@paymentwallresponse')->name('checkout.paymentwallresponse');
    Route::get('thank-you', 'CheckoutController@thank_you')->name('checkout.thankYou');
    Route::get('payment-failed', 'CheckoutController@payment_failed')->name('checkout.paymentFailed');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::post('accounts-update','AccountsController@update')->name('update.accounts');
        Route::post('password-update','AccountsController@passwordupdate')->name('update.password');
        //Paymentwall
        Route::get('paymentwallpay', 'CheckoutController@paymentwall')->name('checkout.paymentwall');
        //Route::post('paymentwallresponse', 'CheckoutController@paymentwallresponse')->name('checkout.paymentwallresponse');

        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
        Route::post("addwishlist", 'ProductController@addwishlist')->name('front.add.addwishlist');
        Route::post("removewishlist", 'ProductController@removewishlist')->name('front.remove.wishlist');
        Route::get("wishlist", 'ProductController@wishlist')->name('front.show.wishlist');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    Route::get("getsubcategory/{slug?}", 'CategoryController@getsubcategory')->name('front.subcategory.slug');
    Route::get("partgroups/{slug?}", 'CategoryController@getpartgroups')->name('front.getpartgroups.slug');
    Route::get("search", 'ProductController@search')->name('search.product');
    Route::get("{product}", 'ProductController@show')->name('front.get.product');

    Route::get("products-page/{ispart}/{make}/{model}", 'CategoryController@showallpartgroups')->name('front.show.all.partgroups');
     /*Route::get("products-page/{ispart}/{make}/{model}", 'ProductController@showallproducts')->name('front.show.all.products');
    */
    Route::get("products/{ispart}/{cateid}/{make}/{model}", 'CategoryController@showallproducts')->name('front.show.all.products');
    Route::get("product-page/{slug}", 'ProductController@showproducts')->name('front.show.product');
});

app/Http/Controllers/Admin/Categories/Requests/CreateCategoryRequest.php
<?php

namespace App\Shop\Categories\Requests;

use App\Shop\Base\BaseFormRequest;

class CreateCategoryRequest extends BaseFormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required', 'unique:categories']
        ];
    }
}

app/Http/Controllers/Admin/Categories/Requests/UpdateCategoryRequest.php
<?php

namespace App\Shop\Categories\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required', Rule::unique('categories')->ignore(request()->segment(3))]
        ];
    }
}

app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Shop\Categories\Repositories\CategoryRepository;
use App\Shop\Categories\Repositories\Interfaces\CategoryRepositoryInterface;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepo;

    /**
     * CategoryController constructor.
     *
     * @param CategoryRepositoryInterface $categoryRepository
     */
    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepo = $categoryRepository;
    }

    /**
     * Find the category via the slug
     *
     * @param string $slug
     * @return \App\Shop\Categories\Category
     */
    public function getCategory(string $slug)
    {
        $category = $this->categoryRepo->findCategoryBySlug(['slug' => $slug]);

        $repo = new CategoryRepository($category);

        $products = $repo->findProducts()->where('status', 1)->all();

        return view('front.categories.category', [
            'category' => $category,
            'products' => $repo->paginateArrayResults($products, 20)
        ]);
    }

    public function tabGetCategory()
    {
        $miancategory = $this->categoryRepo->findBy(['parent_id' => NULL]);
        return view('front.categories.subcategory', [
            'cateslug'=>$slug,
            'miancategory' => $miancategory,
            //'products' => $repo->paginateArrayResults($products, 20)
        ]);
    }

    public function getpartgroups(string $slug ='')
    {
        if($slug){
            $cate = $this->categoryRepo->findOneByOrFail(['slug' => $slug]);
            //dd($cate);
            $submake = $this->categoryRepo->findOneByOrFail(['id' => $cate->parent_id]);
            $make = $this->categoryRepo->findOneByOrFail(['id' => $submake->parent_id]);
            //dd($make);
            $makeName = $make->name;
            $makeSlug = $make->slug;
            $partsGroup = $this->categoryRepo->findBy([ 'is_part' => 1 ]);
        }else{
            $subcategory = $this->categoryRepo->findBy([ 'parent_id' =>NULL]);
            $makeName = '';
            $makeSlug = '';
        }
        $b = isset($_GET['b'])?$_GET['b']:0;
        $m = isset($_GET['m'])?$_GET['m']:0;
        $s = isset($_GET['s'])?$_GET['s']:0;
        //echo "<pre>";print_r($partsGroup);die;
        return view('front.categories.partgroups', [
            'category' => $cate,
            'cateslug'=>$slug,
            'subcategory' => $partsGroup,
            'make' => $makeName,
            'makeSlug'=> $makeSlug,
            'model' => $slug,
            'b' => $b,
            'm' => $m,
            's' => $s
        ]);

    }
    public function getsubcategory(string $slug ='')
    {   
        $bid = 0;
        if($slug){
            $cate = $this->categoryRepo->findOneByOrFail(['slug' => $slug]);
            //$subcategory = $this->categoryRepo->findBy([ 'parent_id' => $cate->id ]);
            $bid = $cate->id;
            $subcategory =$this->categoryRepo->getsubcategory([ 'parent_id' => $cate->id ]);
            /*if($subcategory->count())
                $models = $this->categoryRepo->findBy([ 'parent_id' => $subcategory[0]->id ]);
            else 
                $models = [];*/
            $models = [];
            if($subcategory->count()){
                foreach($subcategory as $sc)
                    $models[$sc->id] = $this->categoryRepo->findBy([ 'parent_id' => $sc->id ]);
            }
            //dd($models);
        }else{
            //$subcategory = $this->categoryRepo->getsubcategory([ 'parent_id' =>NULL]);
            $subcategory = $this->categoryRepo->rootCategories('name', 'asc');
            $models = [];
        }
        //echo "<pre>";print_r($subcategory);die;
        return view('front.categories.subcategory', [
            'cateslug'=>$slug,
            'subcategory' => $subcategory,
            'make' => $slug,
            'models' => $models,
            'bid' => $bid
        ]);
    }

    public function showallpartgroups(string $ispart, string $make, string $model)
    {
        $partgroup = $this->categoryRepo->findCategoryById($ispart);
        $partgroupname = $partgroup->name;
        $partgroups = $this->categoryRepo->getsubcategory([ 'parent_id' =>$ispart ]);
        $mostSearchedParts = [];
        $b = isset($_GET['b'])?$_GET['b']:0;
        $m = isset($_GET['m'])?$_GET['m']:0;
        $s = isset($_GET['s'])?$_GET['s']:0;
        $p = isset($_GET['p'])?$_GET['p']:0;
        if($partgroups->count() > 0){
            $mostSearchedParts = $this->categoryRepo->mostSearchedParts($b, $m, $s, $p);
        }
        //dd($partgroups);
        //die;
        $partgroupsSubCats = [];
        foreach($partgroups as $pg){
            $catsArr = [];
            $subCats = $this->categoryRepo->getsubcategory([ 'parent_id' =>$pg->id ]);
            if($subCats->count()){
                foreach($subCats as $sc){
                    $catsArr[$sc->id] = $sc->name;
                }
            }
            $partgroupsSubCats[$pg->id] = $catsArr;
        }
        //dd($mostSearchedParts);
        
        return view('front.categories.showallpartgroups', compact(
            'mostSearchedParts',
            'partgroup',
            'partgroups',
            'make',
            'model',
            'partgroupname',
            'ispart',
            'partgroupsSubCats',
            'b',
            'm',
            's',
            'p'
        ));
    }

    public function showallproducts(string $ispart, string $cateid, string $make, string $model)
    {
        $b = isset($_GET['b'])?$_GET['b']:0;
        $m = isset($_GET['m'])?$_GET['m']:0;
        $s = isset($_GET['s'])?$_GET['s']:0;
        $p = isset($_GET['p'])?$_GET['p']:0;
        $pi = $cateid;
        $this->categoryRepo->updateView($b, $m, $s, $p, $pi);
        $cate = $this->categoryRepo->findCategoryById($cateid);
        //dd($cate);
        /*$cate->total_views = $cate->total_views + 1;
        $cate->save();*/
        //$products = $cate->products;
        $products = $this->categoryRepo->getProducts($b, $m, $s, $p, $cate->parent_id, $pi);
        //dd($products);
        $partgroup = $this->categoryRepo->findCategoryById($ispart);
        $partgroupname = $partgroup->name;
        $parts= $this->categoryRepo->findCategoryById($cateid);
        $partsname = $parts->name;
        //echo"<pre>";print_r($partsname);die;
        return view('front.products.products-page', compact(
            'products',
            'make',
            'model',
            'partgroupname',
            'partsname',
            'ispart',
            'b',
            'm',
            's',
            'p'
        ));
    }
}

resources/views/admin/categories/carmodel.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($categories)
            <div class="box">
                <div class="box-body">
                    <h2>Car Model</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <td class="col-md-3">Name</td>
                                <td class="col-md-3">Cover</td>
                                <td class="col-md-3">Status</td>
                                <td class="col-md-3">Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>
                                    {{--<a href="{{ route('admin.categories.show', $category->id) }}">{{ $category->name }}</a></td>--}}
                                    {{ $category->name }}
                                <td>
                                    @if(isset($category->cover)  && !empty($category->cover))
                                        <img src="{{ asset("storage/$category->cover") }}" alt="" class="img-responsive">
                                    @endif
                                </td>
                                <td>@include('layouts.status', ['status' => $category->status])</td>
                                <td>
                                    <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <!-- <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a> -->
                                            <a href="{{ url('admin/categories/'.$category->id.'/edit?type=carmodel') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $categories->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.categories.update', $category->id) }}" method="post" class="form" enctype="multipart/form-data">
                <div class="box-body">
                    <input type="hidden" name="_method" value="put">
                    {{ csrf_field() }}
                    <input type="hidden" name="type" value="{{$type}}">
                    @if($type == 'brand')
                        <input type="hidden" name="parent" value="0">
                    @else
                        <div class="form-group">
                            <label for="parent">Parent Category</label>
                            <select name="parent" id="parent" class="form-control select2">
                                <option value="0">No parent</option>
                                @foreach($categories as $cat)
                                    <option @if($cat->id == $category->parent_id) selected="selected" @endif value="{{$cat->id}}">{{$cat->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="name">{{ ucwords($type) }} Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{!! $category->name ?: old('name')  !!}">
                    </div>
                    <div class="form-group hide">
                        <label for="description">Description </label>
                        <textarea class="form-control ckeditor" name="description" id="description" rows="5" placeholder="Description">{!! $category->description ?: old('description')  !!}</textarea>
                    </div>
                    @if(isset($category->cover))
                    <div class="form-group hide">
                        <img src="{{ asset("storage/$category->cover") }}" alt="" class="img-responsive"> <br/>
                        <a onclick="return confirm('Are you sure?')" href="{{ route('admin.category.remove.image', ['category' => $category->id]) }}" class="btn btn-danger">Remove image?</a>
                    </div>
                    @endif
                    <div class="form-group hide">
                        <label for="cover">Cover </label>
                        <input type="file" name="cover" id="cover" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="status">Status </label>
                        <select name="status" id="status" class="form-control">
                            <option value="0" @if($category->status == 0) selected="selected" @endif>Disable</option>
                            <option value="1" @if($category->status == 1) selected="selected" @endif>Enable</option>
                        </select>
                    </div>
                    @if($type == 'brand')
                        <input type="hidden" name="is_part" value="0">
                        <input type="hidden" name="show_on_product" value="0">
                        <input type="hidden" name="available_part[]" value="">
                    @else

                        <div class="form-group">
                            <label for="status">Is Part Group </label>
                            <select name="is_part" id="is_part" class="form-control">
                                <option value="0" @if($category->is_part == 0) selected="selected" @endif>No</option>
                                <option value="1" @if($category->is_part == 1) selected="selected" @endif>Yes</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="status">Show in Products</label>
                            <select name="show_on_product" id="show_on_product" class="form-control">
                                <option value="0" @if($category->show_on_product == 0) selected="selected" @endif>No</option>
                                <option value="1" @if($category->show_on_product == 1) selected="selected" @endif>Yes</option>
                            </select>
                        </div>
                        @if(!$isparts->isEmpty())
                            <?php 
                            $available_part = explode(',', $category->available_part);
                            ?>
                            <div class="form-group" id="available_part_group" >
                                <label for="available_part">Available Parts Group </label>
                                <select name="available_part[]" id="available_part" class="form-control select2" multiple="multiple">
                                    <option value=""></option>
                                    @foreach($isparts as $ispart)
                                        <option value="{{ $ispart->id }}">{{ $ispart->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        @endif
                    @endif
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.categories.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            <?php /*
            var temp = parseInt($('#is_part').val());
            //alert(temp)
            if(temp) $('#available_part_group').hide();
            else $('#available_part_group').show();
            var selectedIsPart = [];
            @foreach($available_part as $isp)
                selectedIsPart.push('{{ $isp }}');
            @endforeach
            $('#available_part').val(selectedIsPart).trigger('change');
            //$('#available_part_group').hide();
            $('#is_part').trigger('change');
            $('#is_part').on('change', function () {
                var isPart = parseInt($(this).val());
                //alert(typeof(isPart)+" "+isPart)
                if(isPart){
                    $('#available_part').val([]).trigger('change');
                    $('#available_part_group').hide();
                }
                else{
                    $('#available_part_group').show();
                }
            });
            */?>
        });
    </script>
@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($categories)
            <div class="box">
                <div class="box-body">
                    <h2>Brands
                        <a style="float:right;" class="btn btn-success btn-sm" href="{{ url('admin/categories/create?type=brand') }}"><i class="fa fa-plus"></i> Create Brand</a>
                    </h2>
                    <table class="table1">
                        <thead>
                            <tr>
                                <td class="col-md-3">Name</td>
                                <!-- <td class="col-md-3">Cover</td>
                                <td class="col-md-3">Status</td> -->
                                <td class="col-md-3">Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>
                                    {{--<a href="{{ route('admin.categories.show', $category->id) }}">{{ $category->name }}</a></td>--}}
                                    {{ $category->name }}
                                {{--
                                <td>
                                    @if(isset($category->cover)  && !empty($category->cover))
                                        <img src="{{ asset("storage/$category->cover") }}" alt="" class="img-responsive">
                                    @endif
                                </td>--}}
                                {{--<td>@include('layouts.status', ['status' => $category->status])</td>--}}
                                <td>
                                    <a href="{{ url('admin/categories/'.$category->id.'?type=carmodel') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> View Car Models</a>
                                    <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post" class="form-horizontal" style="display: inline-block;">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <!-- <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a> -->
                                            <a href="{{ url('admin/categories/'.$category->id.'/edit?type=brand') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $categories->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection